services:
  backend:
    image: todolist-app-backend-prod
    build:
      target: deploy
  frontend:
    image: todolist-app-frontend-prod
    ports:
      - "3000:80"
    build:
      target: deploy
