services:
  backend:
    image: todolist-app-backend-dev
    build:
      target: dev
    volumes:
      - ./backend:/src
  frontend:
    image: todolist-app-frontend-dev
    ports:
      - "3000:5173"
    build:
      target: dev
    volumes:
      - ./frontend:/app
